### ISSUE TITLE
JavaSE 버전 UP

### ISSUE THREAD

**Issue by Won-Hyuk-Lee** [Won-Hyuk-Lee/SweetHome#6]
- [x] 현재 자바 버전의 JRE System Library를 1.6 -> 1.8로 업그레이드(이원혁)
- [x] 현재 자바 버전의 JRE System Library를 1.6 -> 1.8로 업그레이드(박정현)
- [x] 현재 자바 버전의 JRE System Library를 1.6 -> 1.8로 업그레이드(원성진)

**Comment by Won-Hyuk-Lee** [comment]
다들 업그레이드 하고 나면 자기 이슈 체크하고 마무리 하시면 됩니다.

**Comment by wonsungjin** [comment]
업그레이드 완료

**Comment by hinoky4693** [comment]
업그레이드 완료.
